# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These tools allow you to create documentation in the DocBook format and convert them to HTML, PDF, Postscript, and text.
#

unique template rpms/authoring_and_publishing;

include { 'rpms/base' };

"/software/packages"=pkg_repl("VFlib2","2.25.6-25","i386");
"/software/packages"=pkg_repl("Xaw3d","1.5-24","i386");
"/software/packages"=pkg_repl("dialog","1.0.20040731-3","i386");
"/software/packages"=pkg_repl("docbook-dtds","1.0-25","noarch");
"/software/packages"=pkg_repl("docbook-simple","1.0-2","noarch");
"/software/packages"=pkg_repl("docbook-slides","3.3.1-2","noarch");
"/software/packages"=pkg_repl("docbook-style-dsssl","1.78-4","noarch");
"/software/packages"=pkg_repl("docbook-style-xsl","1.65.1-2","noarch");
"/software/packages"=pkg_repl("docbook-utils","0.6.14-4","noarch");
"/software/packages"=pkg_repl("docbook-utils-pdf","0.6.14-4","noarch");
"/software/packages"=pkg_repl("elinks","0.9.2-3.3.5.2","i386");
"/software/packages"=pkg_repl("jadetex","3.12-11","noarch");
"/software/packages"=pkg_repl("linuxdoc-tools","0.9.20-14","i386");
"/software/packages"=pkg_repl("netpbm","10.25-2.EL4.6.el4_6.1","i386");
"/software/packages"=pkg_repl("netpbm-progs","10.25-2.EL4.6.el4_6.1","i386");
"/software/packages"=pkg_repl("openjade","1.3.2-14","i386");
"/software/packages"=pkg_repl("passivetex","1.25-3","noarch");
"/software/packages"=pkg_repl("perl-SGMLSpm","1.03ii-14","noarch");
"/software/packages"=pkg_repl("psutils","1.17-23","i386");
"/software/packages"=pkg_repl("sgml-common","0.6.3-17","noarch");
"/software/packages"=pkg_repl("tetex","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("tetex-afm","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("tetex-dvips","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("tetex-fonts","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("tetex-latex","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("tetex-xdvi","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("w3c-libwww","5.4.0-10.1.RHEL4.2","i386");
"/software/packages"=pkg_repl("xhtml1-dtds","1.0-7","noarch");
"/software/packages"=pkg_repl("xml-common","0.6.3-17","noarch");
"/software/packages"=pkg_repl("xmltex","20020625-3","noarch");
"/software/packages"=pkg_repl("xmlto","0.0.18-4","i386");

