# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/breton_support;


"/software/packages"=pkg_repl("aspell","0.60.3-7.1","i386");
"/software/packages"=pkg_repl("aspell-br","0.50-4.2.2","i386");
"/software/packages"=pkg_repl("aspell-en","6.0-2.1","i386");
"/software/packages"=pkg_repl("basesystem","8.0-5.1.1","noarch");
"/software/packages"=pkg_repl("bash","3.2-32.el5","i386");
"/software/packages"=pkg_repl("db4","4.3.29-10.el5_5.2","i386");
"/software/packages"=pkg_repl("filesystem","2.4.0-3.el5","i386");
"/software/packages"=pkg_repl("gdbm","1.8.0-26.2.1.el5_6.1","i386");
"/software/packages"=pkg_repl("glibc","2.5-65",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.5-65","i386");
"/software/packages"=pkg_repl("info","4.8-14.el5","i386");
"/software/packages"=pkg_repl("libgcc","4.1.2-51.el5","i386");
"/software/packages"=pkg_repl("libstdc++","4.1.2-51.el5","i386");
"/software/packages"=pkg_repl("libtermcap","2.0.8-46.1","i386");
"/software/packages"=pkg_repl("mktemp","1.5-23.2.2","i386");
"/software/packages"=pkg_repl("ncurses","5.5-24.20060715","i386");
"/software/packages"=pkg_repl("perl","5.8.8-32.el5_6.3","i386");
"/software/packages"=pkg_repl("setup","2.5.58-7.el5","noarch");
"/software/packages"=pkg_repl("tzdata","2011h-2.el5","i386");
"/software/packages"=pkg_repl("zlib","1.2.3-4.el5","i386");

