# Template generated by comps2pan.xsl - DO NOT EDIT
#
# The GNU Emacs text editor.
#

unique template rpms/emacs;

include { 'rpms/base' };

"/software/packages"=pkg_repl("Xaw3d","1.5-24","x86_64");
"/software/packages"=pkg_repl("chkfontpath","1.10.0-2","x86_64");
"/software/packages"=pkg_repl("emacs","21.3-19.EL.4","x86_64");
"/software/packages"=pkg_repl("emacs-common","21.3-19.EL.4","x86_64");
"/software/packages"=pkg_repl("emacs-leim","21.3-19.EL.4","x86_64");
"/software/packages"=pkg_repl("emacspeak","17.0-7","i386");
"/software/packages"=pkg_repl("expat","1.95.7-4","i386");
"/software/packages"=pkg_repl("fontconfig","2.2.3-13.el4","i386");
"/software/packages"=pkg_repl("fonts-xorg-75dpi","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("fonts-xorg-base","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("freetype","2.1.9-8.el4.6","i386");
"/software/packages"=pkg_repl("glibc","2.3.4-2.41","i686");
"/software/packages"=pkg_repl("libgcc","3.4.6-10","i386");
"/software/packages"=pkg_repl("libungif","4.1.3-1.el4.2","x86_64");
"/software/packages"=pkg_repl("perl-HTML-Parser","3.55-1.el4","x86_64");
"/software/packages"=pkg_repl("perl-HTML-Tagset","3.03-30","noarch");
"/software/packages"=pkg_repl("perl-URI","1.30-4","noarch");
"/software/packages"=pkg_repl("perl-libwww-perl","5.79-5","noarch");
"/software/packages"=pkg_repl("psgml","1.2.5-4","noarch");
"/software/packages"=pkg_repl("sgml-common","0.6.3-17","noarch");
"/software/packages"=pkg_repl("tcl","8.4.7-4.el4","i386");
"/software/packages"=pkg_repl("tclx","8.3.5-4","i386");
"/software/packages"=pkg_repl("tk","8.4.7-3.el4_6.1","i386");
"/software/packages"=pkg_repl("ttmkfdir","3.0.9-20.el4","x86_64");
"/software/packages"=pkg_repl("xorg-x11-Mesa-libGL","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xorg-x11-libs","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xorg-x11-xfs","6.8.2-1.EL.52","x86_64");
"/software/packages"=pkg_repl("zlib","1.2.1.2-1.2","i386");

