# Template generated by comps2pan.xsl - DO NOT EDIT
#
# The GNU Emacs text editor.
#

unique template rpms/emacs;

include { 'rpms/base' };

"/software/packages"=pkg_repl("Xaw3d","1.5-24","i386");
"/software/packages"=pkg_repl("chkfontpath","1.10.0-2","i386");
"/software/packages"=pkg_repl("emacs","21.3-19.EL.4","i386");
"/software/packages"=pkg_repl("emacs-common","21.3-19.EL.4","i386");
"/software/packages"=pkg_repl("emacs-leim","21.3-19.EL.4","i386");
"/software/packages"=pkg_repl("emacspeak","17.0-7","i386");
"/software/packages"=pkg_repl("fonts-xorg-75dpi","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("fonts-xorg-base","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("libungif","4.1.3-1.el4.2","i386");
"/software/packages"=pkg_repl("perl-HTML-Parser","3.55-1.el4","i386");
"/software/packages"=pkg_repl("perl-HTML-Tagset","3.03-30","noarch");
"/software/packages"=pkg_repl("perl-libwww-perl","5.79-5","noarch");
"/software/packages"=pkg_repl("psgml","1.2.5-4","noarch");
"/software/packages"=pkg_repl("sgml-common","0.6.3-17","noarch");
"/software/packages"=pkg_repl("tclx","8.3.5-4","i386");
"/software/packages"=pkg_repl("ttmkfdir","3.0.9-20.el4","i386");
"/software/packages"=pkg_repl("xorg-x11-xfs","6.8.2-1.EL.52","i386");

