# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This group includes packages for performing mathematical and scientific computations and plotting, as well as unit conversion.
#

unique template rpms/engineering_and_scientific;

include { 'rpms/base' };

"/software/packages"=pkg_repl("R","2.7.1-2.sl4","x86_64");
"/software/packages"=pkg_repl("blas","3.0-25.1","x86_64");
"/software/packages"=pkg_repl("cfitsio","3.006-3","x86_64");
"/software/packages"=pkg_repl("gnuplot","4.0.0-4","x86_64");
"/software/packages"=pkg_repl("lam","7.1.2-15.el4","x86_64");
"/software/packages"=pkg_repl("lam-libs","7.1.2-15.el4","x86_64");
"/software/packages"=pkg_repl("lapack","3.0-25.1","x86_64");
"/software/packages"=pkg_repl("libaio","0.3.105-2","x86_64");
"/software/packages"=pkg_repl("libf2c","3.4.6-10","x86_64");
"/software/packages"=pkg_repl("libgfortran","4.1.2-42.EL4","x86_64");
"/software/packages"=pkg_repl("mpi-selector","1.0.0-2.el4","noarch");
"/software/packages"=pkg_repl("numpy","1.0.4-1","x86_64");
"/software/packages"=pkg_repl("octave","2.1.57-7","x86_64");
"/software/packages"=pkg_repl("openmpi","1.2.5-5.el4","x86_64");
"/software/packages"=pkg_repl("openmpi-libs","1.2.5-5.el4","x86_64");
"/software/packages"=pkg_repl("perl-HTML-Parser","3.55-1.el4","x86_64");
"/software/packages"=pkg_repl("perl-HTML-Tagset","3.03-30","noarch");
"/software/packages"=pkg_repl("pvm","3.4.5-15.el4","x86_64");
"/software/packages"=pkg_repl("texinfo","4.7-5.el4.2","x86_64");
"/software/packages"=pkg_repl("units","1.80-10","x86_64");

