# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These tools allow you to run an FTP server on the system.
#

unique template rpms/ftp_server;

include { 'rpms/base' };

"/software/packages"=pkg_repl("vsftpd","2.0.1-6.el4","x86_64");

