# Template generated by comps2pan.xsl - DO NOT EDIT
#
# FUSE program and plugins
#

unique template rpms/fuse;


"/software/packages"=pkg_repl("MAKEDEV","3.23-1.2","i386");
"/software/packages"=pkg_repl("SysVinit","2.86-17.el5","i386");
"/software/packages"=pkg_repl("audit-libs","1.7.18-2.el5","i386");
"/software/packages"=pkg_repl("basesystem","8.0-5.1.1","noarch");
"/software/packages"=pkg_repl("bash","3.2-32.el5","i386");
"/software/packages"=pkg_repl("binutils","2.17.50.0.6-14.el5","i386");
"/software/packages"=pkg_repl("bzip2-libs","1.0.3-6.el5_5","i386");
"/software/packages"=pkg_repl("chkconfig","1.3.30.2-2.el5","i386");
"/software/packages"=pkg_repl("coreutils","5.97-34.el5","i386");
"/software/packages"=pkg_repl("cpio","2.6-23.el5_4.1","i386");
"/software/packages"=pkg_repl("cracklib","2.8.9-3.3","i386");
"/software/packages"=pkg_repl("cracklib-dicts","2.8.9-3.3","i386");
"/software/packages"=pkg_repl("cyrus-sasl-lib","2.1.22-5.el5_4.3","i386");
"/software/packages"=pkg_repl("db4","4.3.29-10.el5_5.2","i386");
"/software/packages"=pkg_repl("device-mapper","1.02.63-4.el5","i386");
"/software/packages"=pkg_repl("device-mapper-event","1.02.63-4.el5","i386");
"/software/packages"=pkg_repl("device-mapper-multipath","0.4.7-46.el5_7.1","i386");
"/software/packages"=pkg_repl("dmraid","1.0.0.rc13-65.el5","i386");
"/software/packages"=pkg_repl("dmraid-events","1.0.0.rc13-65.el5","i386");
"/software/packages"=pkg_repl("e2fsprogs","1.39-33.el5","i386");
"/software/packages"=pkg_repl("e2fsprogs-libs","1.39-33.el5","i386");
"/software/packages"=pkg_repl("ethtool","6-4.el5","i386");
"/software/packages"=pkg_repl("expat","1.95.8-8.3.el5_5.3","i386");
"/software/packages"=pkg_repl("filesystem","2.4.0-3.el5","i386");
"/software/packages"=pkg_repl("findutils","4.2.27-6.el5","i386");
"/software/packages"=pkg_repl("fuse","2.7.4-8.el5","i386");
"/software/packages"=pkg_repl("fuse-devel","2.7.4-8.el5","i386");
"/software/packages"=pkg_repl("fuse-libs","2.7.4-8.el5","i386");
"/software/packages"=pkg_repl("fuse-smb","0.8.7-1.SL","i386");
"/software/packages"=pkg_repl("fuse-sshfs","2.2-1.SL","i386");
"/software/packages"=pkg_repl("gawk","3.1.5-14.el5","i386");
"/software/packages"=pkg_repl("gdbm","1.8.0-26.2.1.el5_6.1","i386");
"/software/packages"=pkg_repl("glib2","2.12.3-4.el5_3.1","i386");
"/software/packages"=pkg_repl("glibc","2.5-65",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.5-65","i386");
"/software/packages"=pkg_repl("grep","2.5.1-55.el5","i386");
"/software/packages"=pkg_repl("gzip","1.3.5-13.el5","i386");
"/software/packages"=pkg_repl("hmaccalc","0.9.6-3.el5","i386");
"/software/packages"=pkg_repl("info","4.8-14.el5","i386");
"/software/packages"=pkg_repl("initscripts","8.45.38-2.el5","i386");
"/software/packages"=pkg_repl("iproute","2.6.18-11.el5","i386");
"/software/packages"=pkg_repl("iputils","20020927-46.el5","i386");
"/software/packages"=pkg_repl("iscsi-initiator-utils","6.2.0.872-10.el5","i386");
# PKG_KERNEL_NAME can be overridden if not conforming to standard naming scheme
variable PKG_KERNEL_NAME ?= 'kernel'; 
# PKG_KERNEL_RPM_NAME can be overridden if not conforming to standard naming scheme
variable PKG_KERNEL_RPM_NAME ?= {
  rpmname = PKG_KERNEL_NAME;
  if ( length(KERNEL_VARIANT) > 0 ) {
    rpmname = rpmname + '-' + KERNEL_VARIANT;
  };
  rpmname;
};
"/software/packages"=pkg_add(PKG_KERNEL_RPM_NAME,KERNEL_VERSION_NUM,PKG_ARCH_KERNEL,"multi");
"/software/packages"=pkg_repl("keyutils-libs","1.2-1.el5","i386");
"/software/packages"=pkg_repl("kpartx","0.4.7-46.el5_7.1","i386");
"/software/packages"=pkg_repl("krb5-libs","1.6.1-62.el5","i386");
"/software/packages"=pkg_repl("less","436-7.el5","i386");
"/software/packages"=pkg_repl("libacl","2.2.39-6.el5","i386");
"/software/packages"=pkg_repl("libattr","2.4.32-1.1","i386");
"/software/packages"=pkg_repl("libcap","1.10-26","i386");
"/software/packages"=pkg_repl("libgcc","4.1.2-51.el5","i386");
"/software/packages"=pkg_repl("libselinux","1.33.4-5.7.el5","i386");
"/software/packages"=pkg_repl("libsepol","1.15.2-3.el5","i386");
"/software/packages"=pkg_repl("libsmbclient","3.0.33-3.29.el5_7.4","i386");
"/software/packages"=pkg_repl("libstdc++","4.1.2-51.el5","i386");
"/software/packages"=pkg_repl("libsysfs","2.1.0-1.el5","i386");
"/software/packages"=pkg_repl("libtalloc","2.0.1-11.el5","i386");
"/software/packages"=pkg_repl("libtdb","1.2.1-6.el5","i386");
"/software/packages"=pkg_repl("libtermcap","2.0.8-46.1","i386");
"/software/packages"=pkg_repl("libutempter","1.1.4-4.el5","i386");
"/software/packages"=pkg_repl("logrotate","3.7.4-12","i386");
"/software/packages"=pkg_repl("lvm2","2.02.84-6.el5_7.1","i386");
"/software/packages"=pkg_repl("mcstrans","0.2.11-3.el5","i386");
"/software/packages"=pkg_repl("mingetty","1.07-5.2.2","i386");
"/software/packages"=pkg_repl("mkinitrd","5.1.19.6-71.el5","i386");
"/software/packages"=pkg_repl("mktemp","1.5-23.2.2","i386");
"/software/packages"=pkg_repl("module-init-tools","3.3-0.pre3.1.60.el5_5.1","i386");
"/software/packages"=pkg_repl("nash","5.1.19.6-71.el5","i386");
"/software/packages"=pkg_repl("ncurses","5.5-24.20060715","i386");
"/software/packages"=pkg_repl("net-tools","1.60-81.el5","i386");
"/software/packages"=pkg_repl("nspr","4.8.6-1.el5","i386");
"/software/packages"=pkg_repl("nss","3.12.8-4.el5_6","i386");
"/software/packages"=pkg_repl("openldap","2.3.43-12.el5_6.7","i386");
"/software/packages"=pkg_repl("openssl","0.9.8e-20.el5",PKG_ARCH_OPENSSL);
"/software/packages"=pkg_repl("pam","0.99.6.2-6.el5_5.2","i386");
"/software/packages"=pkg_repl("pcre","6.6-6.el5_6.1","i386");
"/software/packages"=pkg_repl("pkgconfig","0.21-2.el5","i386");
"/software/packages"=pkg_repl("popt","1.10.2.3-22.el5","i386");
"/software/packages"=pkg_repl("procps","3.2.7-17.el5","i386");
"/software/packages"=pkg_repl("psmisc","22.2-7.el5_6.2","i386");
"/software/packages"=pkg_repl("python","2.4.3-44.el5","i386");
"/software/packages"=pkg_repl("python-libs","2.4.3-44.el5","i386");
"/software/packages"=pkg_repl("readline","5.1-3.el5","i386");
"/software/packages"=pkg_repl("rsyslog","3.22.1-3.el5_6.1","i386");
"/software/packages"=pkg_repl("samba-common","3.0.33-3.29.el5_7.4","i386");
"/software/packages"=pkg_repl("samba3x-common","3.5.4-0.83.el5_7.2","i386");
"/software/packages"=pkg_repl("samba3x-winbind","3.5.4-0.83.el5_7.2","i386");
"/software/packages"=pkg_repl("sed","4.1.5-8.el5","i386");
"/software/packages"=pkg_repl("setup","2.5.58-7.el5","noarch");
"/software/packages"=pkg_repl("sgpio","1.2.0_10-2.el5","i386");
"/software/packages"=pkg_repl("shadow-utils","4.0.17-18.el5_6.1","i386");
"/software/packages"=pkg_repl("tar","1.15.1-30.el5","i386");
"/software/packages"=pkg_repl("tzdata","2011h-2.el5","i386");
"/software/packages"=pkg_repl("udev","095-14.27.el5","i386");
"/software/packages"=pkg_repl("util-linux","2.13-0.56.el5","i386");
"/software/packages"=pkg_repl("which","2.16-7","i386");
"/software/packages"=pkg_repl("zlib","1.2.3-4.el5","i386");

