# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Various ways to relax and spend your free time.
#

unique template rpms/games;

include { 'rpms/base' };

"/software/packages"=pkg_repl("GConf2","2.8.1-2.el4","i386");
"/software/packages"=pkg_repl("ORBit2","2.12.0-3","i386");
"/software/packages"=pkg_repl("VFlib2","2.25.6-25","i386");
"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","i386");
"/software/packages"=pkg_repl("arts","1.3.1-2","i386");
"/software/packages"=pkg_repl("atk","1.8.0-2","i386");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","i386");
"/software/packages"=pkg_repl("cdparanoia-libs","alpha9.8-24","i386");
"/software/packages"=pkg_repl("chkfontpath","1.10.0-2","i386");
"/software/packages"=pkg_repl("desktop-backgrounds-basic","2.0-26.2.3SL","noarch");
"/software/packages"=pkg_repl("docbook-dtds","1.0-25","noarch");
"/software/packages"=pkg_repl("esound","0.2.35-2","i386");
"/software/packages"=pkg_repl("fonts-xorg-base","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("ghostscript","7.07-33.2.el4_6.1","i386");
"/software/packages"=pkg_repl("ghostscript-fonts","5.50-13","noarch");
"/software/packages"=pkg_repl("gnome-games","2.8.0-4.rhel4.1","i386");
"/software/packages"=pkg_repl("gnome-keyring","0.4.0-1.2.EL4","i386");
"/software/packages"=pkg_repl("gnome-mime-data","2.4.1-5","i386");
"/software/packages"=pkg_repl("gnome-vfs2","2.8.2-8.7.EL4","i386");
"/software/packages"=pkg_repl("gtk2","2.4.13-24.el4","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("intltool","0.31.2-1","i386");
"/software/packages"=pkg_repl("kdebase","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdegames","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("libIDL","0.8.4-1","i386");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","i386");
"/software/packages"=pkg_repl("libbonobo","2.8.0-2","i386");
"/software/packages"=pkg_repl("libbonoboui","2.8.0.99cvs20040929-2","i386");
"/software/packages"=pkg_repl("libcroco","0.6.0-4","i386");
"/software/packages"=pkg_repl("libglade2","2.4.0-5","i386");
"/software/packages"=pkg_repl("libgnome","2.8.0-2","i386");
"/software/packages"=pkg_repl("libgnomecanvas","2.8.0-1","i386");
"/software/packages"=pkg_repl("libgnomecups","0.1.12-6","i386");
"/software/packages"=pkg_repl("libgnomeprint22","2.8.0-3","i386");
"/software/packages"=pkg_repl("libgnomeprintui22","2.8.0-1","i386");
"/software/packages"=pkg_repl("libgnomeui","2.8.0-1","i386");
"/software/packages"=pkg_repl("libgsf","1.10.1-2","i386");
"/software/packages"=pkg_repl("libidn","0.5.6-1","i386");
"/software/packages"=pkg_repl("libmng","1.0.8-1","i386");
"/software/packages"=pkg_repl("libogg","1.1.2-1","i386");
"/software/packages"=pkg_repl("libraw1394","0.10.1-3","i386");
"/software/packages"=pkg_repl("librsvg2","2.8.1-1.el4.1","i386");
"/software/packages"=pkg_repl("libvorbis","1.1.0-3.el4_6.1","i386");
"/software/packages"=pkg_repl("lm_sensors","2.8.7-2.40.5","i386");
"/software/packages"=pkg_repl("openjade","1.3.2-14","i386");
"/software/packages"=pkg_repl("pango","1.6.0-9","i386");
"/software/packages"=pkg_repl("perl-HTML-Parser","3.55-1.el4","i386");
"/software/packages"=pkg_repl("perl-HTML-Tagset","3.03-30","noarch");
"/software/packages"=pkg_repl("perl-XML-Parser","2.34-5","i386");
"/software/packages"=pkg_repl("perl-libwww-perl","5.79-5","noarch");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","i386");
"/software/packages"=pkg_repl("redhat-artwork","0.120.1-1.2SL.2","i386");
"/software/packages"=pkg_repl("samba-common","3.0.28-0.el4.9","i386");
"/software/packages"=pkg_repl("scrollkeeper","0.3.14-3","i386");
"/software/packages"=pkg_repl("sgml-common","0.6.3-17","noarch");
"/software/packages"=pkg_repl("shared-mime-info","0.15-10.1.el4","i386");
"/software/packages"=pkg_repl("ttmkfdir","3.0.9-20.el4","i386");
"/software/packages"=pkg_repl("urw-fonts","2.2-6.1","noarch");
"/software/packages"=pkg_repl("xml-common","0.6.3-17","noarch");
"/software/packages"=pkg_repl("xorg-x11-xfs","6.8.2-1.EL.52","i386");

