# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This group includes packages to help you manipulate and scan images.
#

unique template rpms/graphics;

include { 'rpms/base' };
include { 'rpms/base_x' };

"/software/packages"=pkg_repl("ImageMagick","6.0.7.1-20.el4","x86_64");
"/software/packages"=pkg_repl("arts","1.3.1-2","x86_64");
"/software/packages"=pkg_repl("cdparanoia-libs","alpha9.8-24","x86_64");
"/software/packages"=pkg_repl("dia","0.94-5.7.2","x86_64");
"/software/packages"=pkg_repl("gd","2.0.28-5.4E.el4_6.1","x86_64");
"/software/packages"=pkg_repl("gdk-pixbuf","0.22.0-17.el4.3","x86_64");
"/software/packages"=pkg_repl("gimp","2.0.5-7.0.7.el4","x86_64");
"/software/packages"=pkg_repl("gimp-data-extras","1.2.0-12","noarch");
"/software/packages"=pkg_repl("gimp-gap","2.0.2-2","x86_64");
"/software/packages"=pkg_repl("gimp-help","2-0.1.0.3","noarch");
"/software/packages"=pkg_repl("gimp-print","4.2.7-2","x86_64");
"/software/packages"=pkg_repl("gimp-print-plugin","4.2.7-2","x86_64");
"/software/packages"=pkg_repl("gphoto2","2.1.4-7","x86_64");
"/software/packages"=pkg_repl("gtk+","1.2.10-36","x86_64");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("imlib","1.9.13-23","x86_64");
"/software/packages"=pkg_repl("kdebase","3.3.1-11.el4","x86_64");
"/software/packages"=pkg_repl("kdegraphics","3.3.1-10.el4","x86_64");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","x86_64");
"/software/packages"=pkg_repl("libexif","0.5.12-5.1.0.2.el4_6.1","x86_64");
"/software/packages"=pkg_repl("libidn","0.5.6-1","x86_64");
"/software/packages"=pkg_repl("libieee1284","0.2.8-4","x86_64");
"/software/packages"=pkg_repl("libmng","1.0.8-1","x86_64");
"/software/packages"=pkg_repl("libraw1394","0.10.1-3","x86_64");
"/software/packages"=pkg_repl("libungif","4.1.3-1.el4.2","x86_64");
"/software/packages"=pkg_repl("libwmf","0.2.8.3-5.7","x86_64");
"/software/packages"=pkg_repl("netpbm","10.25-2.EL4.6.el4_6.1","x86_64");
"/software/packages"=pkg_repl("netpbm-progs","10.25-2.EL4.6.el4_6.1","x86_64");
"/software/packages"=pkg_repl("openmotif","2.2.3-10.2.el4","x86_64");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("sane-backends","1.0.14-6.el4.1","x86_64");
"/software/packages"=pkg_repl("sane-frontends","1.0.12-4","x86_64");
"/software/packages"=pkg_repl("transfig","3.2.4-8","x86_64");
"/software/packages"=pkg_repl("xfig","3.2.4-5","x86_64");
"/software/packages"=pkg_repl("xpdf","3.00-16.el4","x86_64");
"/software/packages"=pkg_repl("xsane","0.92-13","x86_64");
"/software/packages"=pkg_repl("xsane-gimp","0.92-13","x86_64");

