# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/hungarian_support;

include { 'rpms/iso8859_2_support' };

"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","x86_64");
"/software/packages"=pkg_repl("apr","0.9.4-24.9.sl4","x86_64");
"/software/packages"=pkg_repl("apr-util","0.9.4-22.el4","x86_64");
"/software/packages"=pkg_repl("arts","1.3.1-2","x86_64");
"/software/packages"=pkg_repl("aspell","0.50.5-4.EL4","x86_64");
"/software/packages"=pkg_repl("aspell-en","0.51-11","x86_64");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","x86_64");
"/software/packages"=pkg_repl("cups-libs","1.1.22-0.rc1.9.27","x86_64");
"/software/packages"=pkg_repl("cyrus-sasl","2.1.19-14","x86_64");
"/software/packages"=pkg_repl("cyrus-sasl-md5","2.1.19-14","x86_64");
"/software/packages"=pkg_repl("desktop-backgrounds-basic","2.0-26.2.3SL","noarch");
"/software/packages"=pkg_repl("desktop-file-utils","0.9-3.el4","x86_64");
"/software/packages"=pkg_repl("esound","0.2.35-2","x86_64");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","x86_64");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("httpd","2.0.52-41.sl4","x86_64");
"/software/packages"=pkg_repl("httpd-suexec","2.0.52-41.sl4","x86_64");
"/software/packages"=pkg_repl("kde-i18n-Hungarian","3.3.1-2.1","noarch");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","x86_64");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","x86_64");
"/software/packages"=pkg_repl("libgcrypt","1.2.0-3","x86_64");
"/software/packages"=pkg_repl("libgpg-error","1.0-1","x86_64");
"/software/packages"=pkg_repl("libidn","0.5.6-1","x86_64");
"/software/packages"=pkg_repl("libjpeg","6b-33","x86_64");
"/software/packages"=pkg_repl("libmng","1.0.8-1","x86_64");
"/software/packages"=pkg_repl("libogg","1.1.2-1","x86_64");
"/software/packages"=pkg_repl("libpng","1.2.7-3.el4_5.1","x86_64");
"/software/packages"=pkg_repl("libtiff","3.6.1-12.el4_7.2","x86_64");
"/software/packages"=pkg_repl("libvorbis","1.1.0-3.el4_6.1","x86_64");
"/software/packages"=pkg_repl("libxml2","2.6.16-12.5","x86_64");
"/software/packages"=pkg_repl("libxslt","1.1.11-1.el4_7.2.sl","x86_64");
"/software/packages"=pkg_repl("mod_perl","1.99_16-4.5","x86_64");
"/software/packages"=pkg_repl("openldap","2.2.13-12.el4","x86_64");
"/software/packages"=pkg_repl("perl","5.8.5-36.el4_6.3","x86_64");
"/software/packages"=pkg_repl("perl-Filter","1.30-6","x86_64");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("redhat-artwork","0.120.1-1.2SL.2","x86_64");
"/software/packages"=pkg_repl("redhat-logos","1.1.25-1.SL.8","noarch");
"/software/packages"=pkg_repl("redhat-menus","3.7.1-2","noarch");

