# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Fast and small X11 window manager.
#

unique template rpms/ice_desktop;

include { 'rpms/dialup' };
include { 'rpms/base_x' };

"/software/packages"=pkg_repl("gdk-pixbuf","0.22.0-17.el4.3","x86_64");
"/software/packages"=pkg_repl("glib","1.2.10-15","x86_64");
"/software/packages"=pkg_repl("gtk+","1.2.10-36","x86_64");
"/software/packages"=pkg_repl("icewm","1.2.35-1","x86_64");
"/software/packages"=pkg_repl("icewm-l10n","1.2.35-1","x86_64");
"/software/packages"=pkg_repl("imlib","1.9.13-23","x86_64");
"/software/packages"=pkg_repl("libungif","4.1.3-1.el4.2","x86_64");

