# Template generated by comps2pan.xsl - DO NOT EDIT
#
# A lightweight window manager for the X Window System.
#

unique template rpms/ice_desktop;


"/software/packages"=pkg_repl("audit-libs","2.2-2.el6","x86_64");
"/software/packages"=pkg_repl("basesystem","10.0-4.el6","noarch");
"/software/packages"=pkg_repl("bash","4.1.2-14.el6","x86_64");
"/software/packages"=pkg_repl("coreutils","8.4-19.el6","x86_64");
"/software/packages"=pkg_repl("coreutils-libs","8.4-19.el6","x86_64");
"/software/packages"=pkg_repl("cracklib","2.8.16-4.el6","x86_64");
"/software/packages"=pkg_repl("cracklib-dicts","2.8.16-4.el6","x86_64");
"/software/packages"=pkg_repl("db4","4.7.25-17.el6","x86_64");
"/software/packages"=pkg_repl("expat","2.0.1-11.el6_2","x86_64");
"/software/packages"=pkg_repl("filesystem","2.4.30-3.el6","x86_64");
"/software/packages"=pkg_repl("fontconfig","2.8.0-3.el6","x86_64");
"/software/packages"=pkg_repl("freetype","2.3.11-14.el6_3.1","x86_64");
"/software/packages"=pkg_repl("giflib","4.1.6-3.1.el6","x86_64");
"/software/packages"=pkg_repl("glib","1.2.10-33.el6","x86_64");
"/software/packages"=pkg_repl("glibc","2.12-1.107.el6",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12-1.107.el6","x86_64");
"/software/packages"=pkg_repl("gmp","4.3.1-7.el6_2.2","x86_64");
"/software/packages"=pkg_repl("grep","2.6.3-3.el6","x86_64");
"/software/packages"=pkg_repl("groff","1.18.1.4-21.el6","x86_64");
"/software/packages"=pkg_repl("gtk+","1.2.10-70.el6","x86_64");
"/software/packages"=pkg_repl("gzip","1.3.12-18.el6","x86_64");
"/software/packages"=pkg_repl("icewm","1.2.37-1.2","x86_64");
"/software/packages"=pkg_repl("icewm-l10n","1.2.37-1.2","x86_64");
"/software/packages"=pkg_repl("imlib","1.9.15-14.el6","x86_64");
"/software/packages"=pkg_repl("info","4.13a-8.el6","x86_64");
"/software/packages"=pkg_repl("less","436-10.el6","x86_64");
"/software/packages"=pkg_repl("libICE","1.0.6-1.el6","x86_64");
"/software/packages"=pkg_repl("libSM","1.2.1-2.el6","x86_64");
"/software/packages"=pkg_repl("libX11","1.5.0-4.el6","x86_64");
"/software/packages"=pkg_repl("libX11-common","1.5.0-4.el6","noarch");
"/software/packages"=pkg_repl("libXau","1.0.6-4.el6","x86_64");
"/software/packages"=pkg_repl("libXaw","1.0.11-2.el6","x86_64");
"/software/packages"=pkg_repl("libXext","1.3.1-2.el6","x86_64");
"/software/packages"=pkg_repl("libXft","2.3.1-2.el6","x86_64");
"/software/packages"=pkg_repl("libXi","1.6.1-3.el6","x86_64");
"/software/packages"=pkg_repl("libXinerama","1.1.2-2.el6","x86_64");
"/software/packages"=pkg_repl("libXmu","1.1.1-2.el6","x86_64");
"/software/packages"=pkg_repl("libXpm","3.5.10-2.el6","x86_64");
"/software/packages"=pkg_repl("libXrandr","1.4.0-1.el6","x86_64");
"/software/packages"=pkg_repl("libXrender","0.9.7-2.el6","x86_64");
"/software/packages"=pkg_repl("libXt","1.1.3-1.el6","x86_64");
"/software/packages"=pkg_repl("libacl","2.2.49-6.el6","x86_64");
"/software/packages"=pkg_repl("libattr","2.4.44-7.el6","x86_64");
"/software/packages"=pkg_repl("libcap","2.16-5.5.el6","x86_64");
"/software/packages"=pkg_repl("libgcc","4.4.7-3.el6","x86_64");
"/software/packages"=pkg_repl("libjpeg","6b-46.el6","x86_64");
"/software/packages"=pkg_repl("libpng","1.2.49-1.el6_2","x86_64");
"/software/packages"=pkg_repl("libselinux","2.0.94-5.3.el6","x86_64");
"/software/packages"=pkg_repl("libsepol","2.0.41-4.el6","x86_64");
"/software/packages"=pkg_repl("libstdc++","4.4.7-3.el6","x86_64");
"/software/packages"=pkg_repl("libtiff","3.9.4-9.el6_3","x86_64");
"/software/packages"=pkg_repl("libutempter","1.1.5-4.1.el6","x86_64");
"/software/packages"=pkg_repl("libuuid","2.17.2-12.9.el6","x86_64");
"/software/packages"=pkg_repl("libxcb","1.8.1-1.el6","x86_64");
"/software/packages"=pkg_repl("ncurses","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.9-11.el6","x86_64");
"/software/packages"=pkg_repl("pam","1.1.1-13.el6","x86_64");
"/software/packages"=pkg_repl("pcre","7.8-6.el6","x86_64");
"/software/packages"=pkg_repl("sed","4.2.1-10.el6","x86_64");
"/software/packages"=pkg_repl("setup","2.8.14-20.el6","noarch");
"/software/packages"=pkg_repl("shadow-utils","4.1.4.2-13.el6","x86_64");
"/software/packages"=pkg_repl("tzdata","2012j-1.el6","noarch");
"/software/packages"=pkg_repl("xterm","253-1.el6","x86_64");
"/software/packages"=pkg_repl("zlib","1.2.3-29.el6","x86_64");

