# Template generated by comps2pan.xsl - DO NOT EDIT
#
# KDE is a powerful, graphical user interface which includes a panel, desktop, system icons, and a graphical file manager.
#

unique template rpms/kde_desktop;

include { 'rpms/dialup' };
include { 'rpms/base_x' };

"/software/packages"=pkg_repl("SDL","1.2.7-8","i386");
"/software/packages"=pkg_repl("arts","1.3.1-2","i386");
"/software/packages"=pkg_repl("aspell","0.50.5-4.EL4","i386");
"/software/packages"=pkg_repl("aspell-en","0.51-11","i386");
"/software/packages"=pkg_repl("autorun","3.14-2","i386");
"/software/packages"=pkg_repl("cdparanoia-libs","alpha9.8-24","i386");
"/software/packages"=pkg_repl("dbus-x11","0.22-12.EL.9","i386");
"/software/packages"=pkg_repl("desktop-printing","0.17-3.EL.1","i386");
"/software/packages"=pkg_repl("flac","1.1.0-7.el4_5.2","i386");
"/software/packages"=pkg_repl("gdk-pixbuf","0.22.0-17.el4.3","i386");
"/software/packages"=pkg_repl("glib","1.2.10-15","i386");
"/software/packages"=pkg_repl("gphoto2","2.1.4-7","i386");
"/software/packages"=pkg_repl("gtk+","1.2.10-36","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("htdig","3.2.0b6-6.el4_7","i386");
"/software/packages"=pkg_repl("imlib","1.9.13-23","i386");
"/software/packages"=pkg_repl("kdeaddons","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdeadmin","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdeartwork","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdebase","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdegraphics","3.3.1-10.el4","i386");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdemultimedia","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdenetwork","3.3.1-2.3","i386");
"/software/packages"=pkg_repl("kdepim","3.3.1-2.2","i386");
"/software/packages"=pkg_repl("kdeutils","3.3.1-2","i386");
"/software/packages"=pkg_repl("libexif","0.5.12-5.1.0.2.el4_6.1","i386");
"/software/packages"=pkg_repl("libidn","0.5.6-1","i386");
"/software/packages"=pkg_repl("libieee1284","0.2.8-4","i386");
"/software/packages"=pkg_repl("libmng","1.0.8-1","i386");
"/software/packages"=pkg_repl("libraw1394","0.10.1-3","i386");
"/software/packages"=pkg_repl("libungif","4.1.3-1.el4.2","i386");
"/software/packages"=pkg_repl("pilot-link","0.11.8-9.RHEL4","i386");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","i386");
"/software/packages"=pkg_repl("sane-backends","1.0.14-6.el4.1","i386");
"/software/packages"=pkg_repl("speex","1.0.4-4.el4_6.1","i386");
"/software/packages"=pkg_repl("wireless-tools","28-0.pre16.3.3.EL4","i386");
"/software/packages"=pkg_repl("xinetd","2.3.13-4.5.el4","i386");
"/software/packages"=pkg_repl("xloadimage","4.1-36.RHEL4","i386");
"/software/packages"=pkg_repl("xscreensaver","4.18-5.rhel4.14","i386");

