# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Install these packages to develop QT and KDE graphical applications.
#

unique template rpms/kde_software_development;

include { 'rpms/x_software_development' };

"/software/packages"=pkg_repl("PyQt","3.13-1","i386");
"/software/packages"=pkg_repl("PyQt-devel","3.13-1","i386");
"/software/packages"=pkg_repl("arts","1.3.1-2","i386");
"/software/packages"=pkg_repl("arts-devel","1.3.1-2","i386");
"/software/packages"=pkg_repl("aspell","0.50.5-4.EL4","i386");
"/software/packages"=pkg_repl("aspell-en","0.51-11","i386");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","i386");
"/software/packages"=pkg_repl("audiofile-devel","0.2.6-1.el4.1","i386");
"/software/packages"=pkg_repl("cdparanoia-devel","alpha9.8-24","i386");
"/software/packages"=pkg_repl("cdparanoia-libs","alpha9.8-24","i386");
"/software/packages"=pkg_repl("chkfontpath","1.10.0-2","i386");
"/software/packages"=pkg_repl("cups-devel","1.1.22-0.rc1.9.27","i386");
"/software/packages"=pkg_repl("desktop-backgrounds-basic","2.0-26.2.3SL","noarch");
"/software/packages"=pkg_repl("desktop-file-utils","0.9-3.el4","i386");
"/software/packages"=pkg_repl("esound","0.2.35-2","i386");
"/software/packages"=pkg_repl("esound-devel","0.2.35-2","i386");
"/software/packages"=pkg_repl("fonts-xorg-base","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("gdk-pixbuf","0.22.0-17.el4.3","i386");
"/software/packages"=pkg_repl("glib","1.2.10-15","i386");
"/software/packages"=pkg_repl("gphoto2","2.1.4-7","i386");
"/software/packages"=pkg_repl("gtk+","1.2.10-36","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("imlib","1.9.13-23","i386");
"/software/packages"=pkg_repl("kdbg","1.2.9-6","i386");
"/software/packages"=pkg_repl("kdebase","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdebase-devel","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdegraphics","3.3.1-10.el4","i386");
"/software/packages"=pkg_repl("kdegraphics-devel","3.3.1-10.el4","i386");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdelibs-devel","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdenetwork","3.3.1-2.3","i386");
"/software/packages"=pkg_repl("kdenetwork-devel","3.3.1-2.3","i386");
"/software/packages"=pkg_repl("kdepim","3.3.1-2.2","i386");
"/software/packages"=pkg_repl("kdepim-devel","3.3.1-2.2","i386");
"/software/packages"=pkg_repl("kdesdk","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdesdk-devel","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdeutils","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdeutils-devel","3.3.1-2","i386");
"/software/packages"=pkg_repl("kdevelop","3.1.1-2","i386");
"/software/packages"=pkg_repl("kernel-utils","2.4-14.1.117","i386");
"/software/packages"=pkg_repl("libart_lgpl-devel","2.3.16-3","i386");
"/software/packages"=pkg_repl("libexif","0.5.12-5.1.0.2.el4_6.1","i386");
"/software/packages"=pkg_repl("libgcrypt","1.2.0-3","i386");
"/software/packages"=pkg_repl("libgpg-error","1.0-1","i386");
"/software/packages"=pkg_repl("libieee1284","0.2.8-4","i386");
"/software/packages"=pkg_repl("libieee1284-devel","0.2.8-4","i386");
"/software/packages"=pkg_repl("libraw1394","0.10.1-3","i386");
"/software/packages"=pkg_repl("libxslt","1.1.11-1.el4_7.2.sl","i386");
"/software/packages"=pkg_repl("libxslt-devel","1.1.11-1.el4_7.2.sl","i386");
"/software/packages"=pkg_repl("lm_sensors","2.8.7-2.40.5","i386");
"/software/packages"=pkg_repl("net-snmp-libs","5.1.2-13.el4","i386");
"/software/packages"=pkg_repl("pcre-devel","4.5-4.el4_6.6","i386");
"/software/packages"=pkg_repl("pilot-link","0.11.8-9.RHEL4","i386");
"/software/packages"=pkg_repl("pilot-link-devel","0.11.8-9.RHEL4","i386");
"/software/packages"=pkg_repl("qt-designer","3.3.3-13.RHEL4","i386");
"/software/packages"=pkg_repl("qt-devel","3.3.3-13.RHEL4","i386");
"/software/packages"=pkg_repl("redhat-artwork","0.120.1-1.2SL.2","i386");
"/software/packages"=pkg_repl("redhat-logos","1.1.25-1.SL.8","noarch");
"/software/packages"=pkg_repl("redhat-menus","3.7.1-2","noarch");
"/software/packages"=pkg_repl("samba-common","3.0.28-0.el4.9","i386");
"/software/packages"=pkg_repl("sane-backends","1.0.14-6.el4.1","i386");
"/software/packages"=pkg_repl("sane-backends-devel","1.0.14-6.el4.1","i386");
"/software/packages"=pkg_repl("sip","4.1-1","i386");
"/software/packages"=pkg_repl("sip-devel","4.1-1","i386");
"/software/packages"=pkg_repl("ttmkfdir","3.0.9-20.el4","i386");
"/software/packages"=pkg_repl("wireless-tools","28-0.pre16.3.3.EL4","i386");
"/software/packages"=pkg_repl("xorg-x11-Mesa-libGLU","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xorg-x11-xfs","6.8.2-1.EL.52","i386");

