# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/kinyarwanda_support;


"/software/packages"=pkg_repl("basesystem","10.0-4.el6","noarch");
"/software/packages"=pkg_repl("bash","4.1.2-8.el6","x86_64");
"/software/packages"=pkg_repl("filesystem","2.4.30-3.el6","x86_64");
"/software/packages"=pkg_repl("glibc","2.12-1.47.el6",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12-1.47.el6","x86_64");
"/software/packages"=pkg_repl("hunspell","1.2.8-16.el6","x86_64");
"/software/packages"=pkg_repl("hunspell-rw","0.20050109-3.1.el6","noarch");
"/software/packages"=pkg_repl("libattr","2.4.44-7.el6","x86_64");
"/software/packages"=pkg_repl("libcap","2.16-5.5.el6","x86_64");
"/software/packages"=pkg_repl("libgcc","4.4.6-3.el6","x86_64");
"/software/packages"=pkg_repl("libstdc++","4.4.6-3.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.9-11.el6","x86_64");
"/software/packages"=pkg_repl("setup","2.8.14-13.el6","noarch");
"/software/packages"=pkg_repl("tzdata","2011l-4.el6","noarch");

