# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/lao_support;


"/software/packages"=pkg_repl("basesystem","10.0-4.el6","noarch");
"/software/packages"=pkg_repl("bash","4.1.2-9.el6_2","x86_64");
"/software/packages"=pkg_repl("dejavu-fonts-common","2.30-2.el6","noarch");
"/software/packages"=pkg_repl("dejavu-sans-fonts","2.30-2.el6","noarch");
"/software/packages"=pkg_repl("filesystem","2.4.30-3.el6","x86_64");
"/software/packages"=pkg_repl("fontpackages-filesystem","1.41-1.1.el6","noarch");
"/software/packages"=pkg_repl("glibc","2.12-1.80.el6",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12-1.80.el6","x86_64");
"/software/packages"=pkg_repl("libattr","2.4.44-7.el6","x86_64");
"/software/packages"=pkg_repl("libcap","2.16-5.5.el6","x86_64");
"/software/packages"=pkg_repl("libgcc","4.4.6-4.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.9-11.el6","x86_64");
"/software/packages"=pkg_repl("setup","2.8.14-16.el6","noarch");
"/software/packages"=pkg_repl("tzdata","2012c-1.el6","noarch");

