# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These packages include servers for old network protocols such as rsh and telnet.
#

unique template rpms/legacy_network_server;

include { 'rpms/base' };

"/software/packages"=pkg_repl("bootparamd","0.17-21.RHEL4","i386");
"/software/packages"=pkg_repl("quagga","0.98.3-4.el4","i386");
"/software/packages"=pkg_repl("rsh-server","0.17-25.4","i386");
"/software/packages"=pkg_repl("rusers","0.17-41.40.3","i386");
"/software/packages"=pkg_repl("rusers-server","0.17-41.40.3","i386");
"/software/packages"=pkg_repl("rwho","0.17-22","i386");
"/software/packages"=pkg_repl("talk-server","0.17-26","i386");
"/software/packages"=pkg_repl("telnet-server","0.17-31.EL4.5","i386");
"/software/packages"=pkg_repl("tftp-server","0.39-3.el4","i386");

