# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These packages allow you to configure an IMAP or Postfix mail server.
#

unique template rpms/mail_server;

include { 'rpms/base' };

"/software/packages"=pkg_repl("curl","7.12.1-11.el4","x86_64");
"/software/packages"=pkg_repl("cyrus-imapd","2.2.12-9.RHEL4","x86_64");
"/software/packages"=pkg_repl("cyrus-imapd-murder","2.2.12-9.RHEL4","x86_64");
"/software/packages"=pkg_repl("cyrus-imapd-nntp","2.2.12-9.RHEL4","x86_64");
"/software/packages"=pkg_repl("cyrus-imapd-utils","2.2.12-9.RHEL4","x86_64");
"/software/packages"=pkg_repl("dovecot","0.99.11-9.EL4","x86_64");
"/software/packages"=pkg_repl("exim","4.43-1.RHEL4.5","x86_64");
"/software/packages"=pkg_repl("gnupg","1.2.6-9","x86_64");
"/software/packages"=pkg_repl("libidn","0.5.6-1","x86_64");
"/software/packages"=pkg_repl("lm_sensors","2.8.7-2.40.5","x86_64");
"/software/packages"=pkg_repl("mailman","2.1.5.1-34.rhel4.6","x86_64");
"/software/packages"=pkg_repl("mysql","4.1.22-2.el4.sl","x86_64");
"/software/packages"=pkg_repl("perl-Archive-Tar","1.30-1.el4","noarch");
"/software/packages"=pkg_repl("perl-Compress-Zlib","1.42-1.el4","x86_64");
"/software/packages"=pkg_repl("perl-Cyrus","2.2.12-9.RHEL4","x86_64");
"/software/packages"=pkg_repl("perl-DBI","1.40-9","x86_64");
"/software/packages"=pkg_repl("perl-Digest-HMAC","1.01-13","noarch");
"/software/packages"=pkg_repl("perl-Digest-SHA1","2.07-5","x86_64");
"/software/packages"=pkg_repl("perl-HTML-Parser","3.55-1.el4","x86_64");
"/software/packages"=pkg_repl("perl-HTML-Tagset","3.03-30","noarch");
"/software/packages"=pkg_repl("perl-IO-String","1.08-1.1.el4","noarch");
"/software/packages"=pkg_repl("perl-IO-Zlib","1.04-4.2.el4","noarch");
"/software/packages"=pkg_repl("perl-Net-DNS","0.48-2.el4","x86_64");
"/software/packages"=pkg_repl("perl-Time-HiRes","1.55-3","x86_64");
"/software/packages"=pkg_repl("perl-URI","1.30-4","noarch");
"/software/packages"=pkg_repl("perl-libwww-perl","5.79-5","noarch");
"/software/packages"=pkg_repl("php","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-mbstring","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-pear","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("postfix","2.2.10-1.2.1.el4_7","x86_64");
"/software/packages"=pkg_repl("postgresql-libs","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("sendmail","8.13.1-3.3.el4","x86_64");
"/software/packages"=pkg_repl("sendmail-cf","8.13.1-3.3.el4","x86_64");
"/software/packages"=pkg_repl("spamassassin","3.2.4-1.el4.1","x86_64");
"/software/packages"=pkg_repl("squirrelmail","1.4.8-4.0.1.el4","noarch");

