# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This package group contains packages useful for use with MySQL.
#

unique template rpms/mysql;

include { 'rpms/base' };

"/software/packages"=pkg_repl("MyODBC","2.50.39-25.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("MySQL-python","1.2.1_p2-1.el4.1","x86_64");
"/software/packages"=pkg_repl("curl","7.12.1-11.el4","x86_64");
"/software/packages"=pkg_repl("e2fsprogs-devel","1.35-12.17.el4","x86_64");
"/software/packages"=pkg_repl("krb5-devel","1.3.4-60.el4","x86_64");
"/software/packages"=pkg_repl("libdbi","0.6.5-10.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("libdbi-dbd-mysql","0.6.5-10.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("libidn","0.5.6-1","x86_64");
"/software/packages"=pkg_repl("libmng","1.0.8-1","x86_64");
"/software/packages"=pkg_repl("mod_auth_mysql","2.6.1-2.2","x86_64");
"/software/packages"=pkg_repl("mx","2.0.5-3","x86_64");
"/software/packages"=pkg_repl("mysql","4.1.22-2.el4.sl","x86_64");
"/software/packages"=pkg_repl("mysql-bench","4.1.22-2.el4.sl","x86_64");
"/software/packages"=pkg_repl("mysql-devel","4.1.22-2.el4.sl","x86_64");
"/software/packages"=pkg_repl("mysql-server","4.1.22-2.el4.sl","x86_64");
"/software/packages"=pkg_repl("mysqlclient10","3.23.58-4.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("openssl-devel","0.9.7a-43.17.el4_6.1","x86_64");
"/software/packages"=pkg_repl("perl-DBD-MySQL","2.9004-3.1","x86_64");
"/software/packages"=pkg_repl("perl-DBI","1.40-9","x86_64");
"/software/packages"=pkg_repl("php","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-mysql","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-pear","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("qt-MySQL","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("qt-ODBC","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("unixODBC","2.2.11-1.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("zlib-devel","1.2.1.2-1.2","x86_64");

