# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These packages include network-based servers such as DHCP, Kerberos and NIS.
#

unique template rpms/network_server;

include { 'rpms/base' };

"/software/packages"=pkg_repl("GConf2","2.8.1-2.el4","i386");
"/software/packages"=pkg_repl("ORBit2","2.12.0-3","i386");
"/software/packages"=pkg_repl("alchemist","1.0.34-1","i386");
"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","i386");
"/software/packages"=pkg_repl("amanda","2.4.4p3-1","i386");
"/software/packages"=pkg_repl("amanda-server","2.4.4p3-1","i386");
"/software/packages"=pkg_repl("atk","1.8.0-2","i386");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","i386");
"/software/packages"=pkg_repl("dhcp","3.0.1-62.EL4","i386");
"/software/packages"=pkg_repl("dhcpv6","0.10-24_EL4","i386");
"/software/packages"=pkg_repl("esound","0.2.35-2","i386");
"/software/packages"=pkg_repl("finger-server","0.17-26.EL4.1","i386");
"/software/packages"=pkg_repl("freeradius","1.0.1-3.RHEL4.5","i386");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("gnome-keyring","0.4.0-1.2.EL4","i386");
"/software/packages"=pkg_repl("gnome-mime-data","2.4.1-5","i386");
"/software/packages"=pkg_repl("gnome-python2","2.6.0-3","i386");
"/software/packages"=pkg_repl("gnome-python2-bonobo","2.6.0-3","i386");
"/software/packages"=pkg_repl("gnome-python2-canvas","2.6.0-3","i386");
"/software/packages"=pkg_repl("gnome-vfs2","2.8.2-8.7.EL4","i386");
"/software/packages"=pkg_repl("gnuplot","4.0.0-4","i386");
"/software/packages"=pkg_repl("gtk2","2.4.13-24.el4","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("iscsi-initiator-utils","4.0.3.0-7","i386");
"/software/packages"=pkg_repl("krb5-server","1.3.4-60.el4","i386");
"/software/packages"=pkg_repl("libIDL","0.8.4-1","i386");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","i386");
"/software/packages"=pkg_repl("libbonobo","2.8.0-2","i386");
"/software/packages"=pkg_repl("libbonoboui","2.8.0.99cvs20040929-2","i386");
"/software/packages"=pkg_repl("libglade2","2.4.0-5","i386");
"/software/packages"=pkg_repl("libgnome","2.8.0-2","i386");
"/software/packages"=pkg_repl("libgnomecanvas","2.8.0-1","i386");
"/software/packages"=pkg_repl("libgnomeui","2.8.0-1","i386");
"/software/packages"=pkg_repl("libtool-libs","1.5.6-4.EL4.2","i386");
"/software/packages"=pkg_repl("lm_sensors","2.8.7-2.40.5","i386");
"/software/packages"=pkg_repl("net-snmp","5.1.2-13.el4","i386");
"/software/packages"=pkg_repl("net-snmp-utils","5.1.2-13.el4","i386");
"/software/packages"=pkg_repl("netdump-server","0.7.16-14","i386");
"/software/packages"=pkg_repl("openldap-servers","2.2.13-12.el4","i386");
"/software/packages"=pkg_repl("opensm","3.1.8-1.el4","i386");
"/software/packages"=pkg_repl("pango","1.6.0-9","i386");
"/software/packages"=pkg_repl("perl-HTML-Parser","3.55-1.el4","i386");
"/software/packages"=pkg_repl("perl-HTML-Tagset","3.03-30","noarch");
"/software/packages"=pkg_repl("pygtk2","2.4.0-2.el4","i386");
"/software/packages"=pkg_repl("pygtk2-libglade","2.4.0-2.el4","i386");
"/software/packages"=pkg_repl("pyorbit","2.0.1-1","i386");
"/software/packages"=pkg_repl("quagga","0.98.3-4.el4","i386");
"/software/packages"=pkg_repl("radvd","0.7.2-10.el4","i386");
"/software/packages"=pkg_repl("rarpd","ss981107-18.40.2","i386");
"/software/packages"=pkg_repl("shared-mime-info","0.15-10.1.el4","i386");
"/software/packages"=pkg_repl("system-config-netboot","0.1.40.1-1.el4","i386");
"/software/packages"=pkg_repl("system-config-netboot-cmd","0.1.40.1-1.el4","i386");
"/software/packages"=pkg_repl("tftp-server","0.39-3.el4","i386");
"/software/packages"=pkg_repl("vnc-server","4.0-12.el4","i386");
"/software/packages"=pkg_repl("ypserv","2.13-19","i386");

