# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This group allows you to configure the system as a news server.
#

unique template rpms/news_server;

include { 'rpms/base' };

"/software/packages"=pkg_repl("inews","2.3.5-12","x86_64");
"/software/packages"=pkg_repl("inn","2.3.5-12","x86_64");

