# Template generated by comps2pan.xsl - DO NOT EDIT
#
# The applications include office suites, PDF viewers, and more.
#

unique template rpms/office;

include { 'rpms/base_x' };

"/software/packages"=pkg_repl("Xaw3d","1.5-24","i386");
"/software/packages"=pkg_repl("arts","1.3.1-2","i386");
"/software/packages"=pkg_repl("aspell","0.50.5-4.EL4","i386");
"/software/packages"=pkg_repl("aspell-en","0.51-11","i386");
"/software/packages"=pkg_repl("cdparanoia-libs","alpha9.8-24","i386");
"/software/packages"=pkg_repl("compat-libstdc++-33","3.2.3-47.3","i386");
"/software/packages"=pkg_repl("ggv","2.8.0-1","i386");
"/software/packages"=pkg_repl("gpdf","2.8.2-7.7.2","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("kdebase","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdepim","3.3.1-2.2","i386");
"/software/packages"=pkg_repl("libidn","0.5.6-1","i386");
"/software/packages"=pkg_repl("libmng","1.0.8-1","i386");
"/software/packages"=pkg_repl("libraw1394","0.10.1-3","i386");
"/software/packages"=pkg_repl("openoffice.org","1.1.5-10.6.0.5.EL4","i386");
"/software/packages"=pkg_repl("openoffice.org-i18n","1.1.5-10.6.0.5.EL4","i386");
"/software/packages"=pkg_repl("openoffice.org-libs","1.1.5-10.6.0.5.EL4","i386");
"/software/packages"=pkg_repl("pilot-link","0.11.8-9.RHEL4","i386");
"/software/packages"=pkg_repl("planner","0.12.1-2.3","i386");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","i386");
"/software/packages"=pkg_repl("tetex-dvips","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("tetex-fonts","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("tetex-xdvi","2.0.2-22.0.1.EL4.10","i386");
"/software/packages"=pkg_repl("unzip","5.51-10.el4","i386");
"/software/packages"=pkg_repl("w3c-libwww","5.4.0-10.1.RHEL4.2","i386");

