# Template generated by comps2pan.xsl - DO NOT EDIT
#
# The applications include office suites, PDF viewers, and more.
#

unique template rpms/office;

include { 'rpms/base_x' };

"/software/packages"=pkg_repl("GConf2","2.8.1-2.el4","i386");
"/software/packages"=pkg_repl("ORBit2","2.12.0-3","i386");
"/software/packages"=pkg_repl("Xaw3d","1.5-24","x86_64");
"/software/packages"=pkg_repl("arts","1.3.1-2","x86_64");
"/software/packages"=pkg_repl("aspell","0.50.5-4.EL4","x86_64");
"/software/packages"=pkg_repl("aspell-en","0.51-11","x86_64");
"/software/packages"=pkg_repl("atk","1.8.0-2","i386");
"/software/packages"=pkg_repl("audit-libs","1.0.16-3.el4","i386");
"/software/packages"=pkg_repl("bzip2-libs","1.0.2-13.EL4.3","i386");
"/software/packages"=pkg_repl("cdparanoia-libs","alpha9.8-24","x86_64");
"/software/packages"=pkg_repl("compat-libstdc++-33","3.2.3-47.3","i386");
"/software/packages"=pkg_repl("db4","4.2.52-7.3.el4","i386");
"/software/packages"=pkg_repl("dbus","0.22-12.EL.9","i386");
"/software/packages"=pkg_repl("dbus-glib","0.22-12.EL.9","i386");
"/software/packages"=pkg_repl("e2fsprogs","1.35-12.17.el4","i386");
"/software/packages"=pkg_repl("expat","1.95.7-4","i386");
"/software/packages"=pkg_repl("fontconfig","2.2.3-13.el4","i386");
"/software/packages"=pkg_repl("freetype","2.1.9-8.el4.6","i386");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("ggv","2.8.0-1","x86_64");
"/software/packages"=pkg_repl("glib2","2.4.7-1","i386");
"/software/packages"=pkg_repl("gnome-vfs2","2.8.2-8.7.EL4","i386");
"/software/packages"=pkg_repl("gpdf","2.8.2-7.7.2","x86_64");
"/software/packages"=pkg_repl("gtk2","2.4.13-24.el4","i386");
"/software/packages"=pkg_repl("hal","0.4.2-8.EL4","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("kdebase","3.3.1-11.el4","x86_64");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","x86_64");
"/software/packages"=pkg_repl("kdepim","3.3.1-2.2","x86_64");
"/software/packages"=pkg_repl("krb5-libs","1.3.4-60.el4","i386");
"/software/packages"=pkg_repl("libIDL","0.8.4-1","i386");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","i386");
"/software/packages"=pkg_repl("libbonobo","2.8.0-2","i386");
"/software/packages"=pkg_repl("libcap","1.10-20","i386");
"/software/packages"=pkg_repl("libidn","0.5.6-1","x86_64");
"/software/packages"=pkg_repl("libjpeg","6b-33","i386");
"/software/packages"=pkg_repl("libmng","1.0.8-1","x86_64");
"/software/packages"=pkg_repl("libpng","1.2.7-3.el4_5.1","i386");
"/software/packages"=pkg_repl("libraw1394","0.10.1-3","x86_64");
"/software/packages"=pkg_repl("libselinux","1.19.1-7.4","i386");
"/software/packages"=pkg_repl("libsilc","0.9.12-7","x86_64");
"/software/packages"=pkg_repl("libstdc++","3.4.6-10","i386");
"/software/packages"=pkg_repl("libtiff","3.6.1-12.el4_7.2","i386");
"/software/packages"=pkg_repl("libxml2","2.6.16-12.5","i386");
"/software/packages"=pkg_repl("openoffice.org","1.1.5-10.6.0.5.EL4","i386");
"/software/packages"=pkg_repl("openoffice.org-i18n","1.1.5-10.6.0.5.EL4","i386");
"/software/packages"=pkg_repl("openoffice.org-libs","1.1.5-10.6.0.5.EL4","i386");
"/software/packages"=pkg_repl("openssl","0.9.7a-43.17.el4_6.1","i686");
"/software/packages"=pkg_repl("pango","1.6.0-9","i386");
"/software/packages"=pkg_repl("pilot-link","0.11.8-9.RHEL4","x86_64");
"/software/packages"=pkg_repl("planner","0.12.1-2.3","x86_64");
"/software/packages"=pkg_repl("popt","1.9.1-26_nonptl","i386");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("redhat-artwork","0.120.1-1.2SL.2","i386");
"/software/packages"=pkg_repl("startup-notification","0.7-1","i386");
"/software/packages"=pkg_repl("tetex-dvips","2.0.2-22.0.1.EL4.10","x86_64");
"/software/packages"=pkg_repl("tetex-fonts","2.0.2-22.0.1.EL4.10","x86_64");
"/software/packages"=pkg_repl("tetex-xdvi","2.0.2-22.0.1.EL4.10","x86_64");
"/software/packages"=pkg_repl("unzip","5.51-10.el4","x86_64");
"/software/packages"=pkg_repl("w3c-libwww","5.4.0-10.1.RHEL4.2","x86_64");
"/software/packages"=pkg_repl("xorg-x11-Mesa-libGL","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xorg-x11-libs","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("zlib","1.2.1.2-1.2","i386");

