# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Various Yum Repositories.  These are not supported by Scientific Linux but are here for your convenience.
#

unique template rpms/repos;


"/software/packages"=pkg_repl("atrpms-repo","6-5.el6","x86_64");
"/software/packages"=pkg_repl("basesystem","10.0-4.el6","noarch");
"/software/packages"=pkg_repl("bash","4.1.2-8.el6","x86_64");
"/software/packages"=pkg_repl("elrepo-release","6-4.el6.elrepo","noarch");
"/software/packages"=pkg_repl("epel-release","6-5","noarch");
"/software/packages"=pkg_repl("filesystem","2.4.30-3.el6","x86_64");
"/software/packages"=pkg_repl("glibc","2.12-1.47.el6",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12-1.47.el6","x86_64");
"/software/packages"=pkg_repl("libattr","2.4.44-7.el6","x86_64");
"/software/packages"=pkg_repl("libcap","2.16-5.5.el6","x86_64");
"/software/packages"=pkg_repl("libgcc","4.4.6-3.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.9-11.el6","x86_64");
"/software/packages"=pkg_repl("rpmforge-release","0.5.2-2.el6.rf","x86_64");
"/software/packages"=pkg_repl("setup","2.8.14-13.el6","noarch");
"/software/packages"=pkg_repl("sl-release","6.2-1.1","x86_64");
"/software/packages"=pkg_repl("tzdata","2011l-4.el6","noarch");

