# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Basic support for the Ruby programming language.
#

unique template rpms/ruby;

include { 'rpms/base' };

"/software/packages"=pkg_repl("emacs-common","21.3-19.EL.4","i386");
"/software/packages"=pkg_repl("ruby","1.8.1-7.el4_6.1","i386");
"/software/packages"=pkg_repl("ruby-devel","1.8.1-7.el4_6.1","i386");
"/software/packages"=pkg_repl("ruby-libs","1.8.1-7.el4_6.1","i386");
"/software/packages"=pkg_repl("ruby-mode","1.8.1-7.el4_6.1","i386");

