# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Ruby interfaces to common libraries and functionality.
#

unique template rpms/ruby_runtime;


"/software/packages"=pkg_repl("audit-libs","2.2-2.el6","x86_64");
"/software/packages"=pkg_repl("basesystem","10.0-4.el6","noarch");
"/software/packages"=pkg_repl("bash","4.1.2-9.el6_2","x86_64");
"/software/packages"=pkg_repl("ca-certificates","2010.63-3.el6_1.5","noarch");
"/software/packages"=pkg_repl("compat-readline5","5.2-17.1.el6","x86_64");
"/software/packages"=pkg_repl("coreutils","8.4-19.el6","x86_64");
"/software/packages"=pkg_repl("coreutils-libs","8.4-19.el6","x86_64");
"/software/packages"=pkg_repl("cracklib","2.8.16-4.el6","x86_64");
"/software/packages"=pkg_repl("cracklib-dicts","2.8.16-4.el6","x86_64");
"/software/packages"=pkg_repl("db4","4.7.25-17.el6","x86_64");
"/software/packages"=pkg_repl("filesystem","2.4.30-3.el6","x86_64");
"/software/packages"=pkg_repl("gdbm","1.8.0-36.el6","x86_64");
"/software/packages"=pkg_repl("glibc","2.12-1.80.el6",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12-1.80.el6","x86_64");
"/software/packages"=pkg_repl("gmp","4.3.1-7.el6_2.2","x86_64");
"/software/packages"=pkg_repl("grep","2.6.3-3.el6","x86_64");
"/software/packages"=pkg_repl("groff","1.18.1.4-21.el6","x86_64");
"/software/packages"=pkg_repl("gzip","1.3.12-18.el6","x86_64");
"/software/packages"=pkg_repl("info","4.13a-8.el6","x86_64");
"/software/packages"=pkg_repl("keyutils-libs","1.4-4.el6","x86_64");
"/software/packages"=pkg_repl("krb5-libs","1.9-33.el6","x86_64");
"/software/packages"=pkg_repl("less","436-10.el6","x86_64");
"/software/packages"=pkg_repl("libacl","2.2.49-6.el6","x86_64");
"/software/packages"=pkg_repl("libattr","2.4.44-7.el6","x86_64");
"/software/packages"=pkg_repl("libcap","2.16-5.5.el6","x86_64");
"/software/packages"=pkg_repl("libcom_err","1.41.12-12.el6","x86_64");
"/software/packages"=pkg_repl("libgcc","4.4.6-4.el6","x86_64");
"/software/packages"=pkg_repl("libselinux","2.0.94-5.3.el6","x86_64");
"/software/packages"=pkg_repl("libsepol","2.0.41-4.el6","x86_64");
"/software/packages"=pkg_repl("libstdc++","4.4.6-4.el6","x86_64");
"/software/packages"=pkg_repl("ncurses","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.9-11.el6","x86_64");
"/software/packages"=pkg_repl("openssl","1.0.0-20.el6_2.5",PKG_ARCH_OPENSSL);
"/software/packages"=pkg_repl("pam","1.1.1-10.el6_2.1","x86_64");
"/software/packages"=pkg_repl("pcre","7.8-4.el6","x86_64");
"/software/packages"=pkg_repl("ruby","1.8.7.352-7.el6_2","x86_64");
"/software/packages"=pkg_repl("ruby-irb","1.8.7.352-7.el6_2","x86_64");
"/software/packages"=pkg_repl("ruby-libs","1.8.7.352-7.el6_2","x86_64");
"/software/packages"=pkg_repl("sed","4.2.1-10.el6","x86_64");
"/software/packages"=pkg_repl("setup","2.8.14-16.el6","noarch");
"/software/packages"=pkg_repl("tzdata","2012c-1.el6","noarch");
"/software/packages"=pkg_repl("zlib","1.2.3-27.el6","x86_64");

