# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/russian_support;

include { 'rpms/cyrillic_support' };

"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","i386");
"/software/packages"=pkg_repl("arts","1.3.1-2","i386");
"/software/packages"=pkg_repl("aspell","0.50.5-4.EL4","i386");
"/software/packages"=pkg_repl("aspell-en","0.51-11","i386");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","i386");
"/software/packages"=pkg_repl("cups-libs","1.1.22-0.rc1.9.27","i386");
"/software/packages"=pkg_repl("desktop-backgrounds-basic","2.0-26.2.3SL","noarch");
"/software/packages"=pkg_repl("desktop-file-utils","0.9-3.el4","i386");
"/software/packages"=pkg_repl("esound","0.2.35-2","i386");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("kde-i18n-Russian","3.3.1-2.1","noarch");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","i386");
"/software/packages"=pkg_repl("libgcrypt","1.2.0-3","i386");
"/software/packages"=pkg_repl("libgpg-error","1.0-1","i386");
"/software/packages"=pkg_repl("libidn","0.5.6-1","i386");
"/software/packages"=pkg_repl("libmng","1.0.8-1","i386");
"/software/packages"=pkg_repl("libogg","1.1.2-1","i386");
"/software/packages"=pkg_repl("libtiff","3.6.1-12.el4_7.2","i386");
"/software/packages"=pkg_repl("libvorbis","1.1.0-3.el4_6.1","i386");
"/software/packages"=pkg_repl("libxml2","2.6.16-12.5","i386");
"/software/packages"=pkg_repl("libxslt","1.1.11-1.el4_7.2.sl","i386");
"/software/packages"=pkg_repl("man-pages-ru","0.7-8","noarch");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","i386");
"/software/packages"=pkg_repl("redhat-artwork","0.120.1-1.2SL.2","i386");
"/software/packages"=pkg_repl("redhat-logos","1.1.25-1.SL.8","noarch");
"/software/packages"=pkg_repl("redhat-menus","3.7.1-2","noarch");

