# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Support for large, highly scalable, filesystems.
#

unique template rpms/scalable_file_systems;


"/software/packages"=pkg_repl("attr","2.4.44-7.el6","x86_64");
"/software/packages"=pkg_repl("basesystem","10.0-4.el6","noarch");
"/software/packages"=pkg_repl("bash","4.1.2-14.el6","x86_64");
"/software/packages"=pkg_repl("filesystem","2.4.30-3.el6","x86_64");
"/software/packages"=pkg_repl("glibc","2.12-1.107.el6",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12-1.107.el6","x86_64");
"/software/packages"=pkg_repl("info","4.13a-8.el6","x86_64");
"/software/packages"=pkg_repl("libattr","2.4.44-7.el6","x86_64");
"/software/packages"=pkg_repl("libblkid","2.17.2-12.9.el6","x86_64");
"/software/packages"=pkg_repl("libcap","2.16-5.5.el6","x86_64");
"/software/packages"=pkg_repl("libgcc","4.4.7-3.el6","x86_64");
"/software/packages"=pkg_repl("libuuid","2.17.2-12.9.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-3.20090208.el6","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.9-11.el6","x86_64");
"/software/packages"=pkg_repl("readline","6.0-4.el6","x86_64");
"/software/packages"=pkg_repl("setup","2.8.14-20.el6","noarch");
"/software/packages"=pkg_repl("tzdata","2012j-1.el6","noarch");
"/software/packages"=pkg_repl("xfsdump","3.0.4-3.el6","x86_64");
"/software/packages"=pkg_repl("xfsprogs","3.1.1-10.el6","x86_64");
"/software/packages"=pkg_repl("zlib","1.2.3-29.el6","x86_64");

