# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/server;

include { 'rpms/server_cfg' };
include { 'rpms/dialup' };
include { 'rpms/printing' };
include { 'rpms/admin_tools' };
include { 'rpms/text_internet' };
include { 'rpms/base' };
include { 'rpms/web_server' };
include { 'rpms/smb_server' };
include { 'rpms/yum' };
include { 'rpms/apt_rpm' };


