# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This group contains all of Scientific Linux's custom server configuration tools.
#

unique template rpms/server_cfg;

include { 'rpms/base' };

"/software/packages"=pkg_repl("4Suite","1.0-3","i386");
"/software/packages"=pkg_repl("GConf2","2.8.1-2.el4","i386");
"/software/packages"=pkg_repl("ORBit2","2.12.0-3","i386");
"/software/packages"=pkg_repl("Omni","0.9.1-7.1","i386");
"/software/packages"=pkg_repl("Omni-foomatic","0.9.1-7.1","i386");
"/software/packages"=pkg_repl("PyXML","0.8.3-6","i386");
"/software/packages"=pkg_repl("VFlib2","2.25.6-25","i386");
"/software/packages"=pkg_repl("alchemist","1.0.34-1","i386");
"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","i386");
"/software/packages"=pkg_repl("atk","1.8.0-2","i386");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","i386");
"/software/packages"=pkg_repl("chkfontpath","1.10.0-2","i386");
"/software/packages"=pkg_repl("esound","0.2.35-2","i386");
"/software/packages"=pkg_repl("fonts-xorg-base","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("foomatic","3.0.2-3.1","i386");
"/software/packages"=pkg_repl("gail","1.8.0-2","i386");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("ghostscript","7.07-33.2.el4_6.1","i386");
"/software/packages"=pkg_repl("ghostscript-fonts","5.50-13","noarch");
"/software/packages"=pkg_repl("gnome-keyring","0.4.0-1.2.EL4","i386");
"/software/packages"=pkg_repl("gnome-mime-data","2.4.1-5","i386");
"/software/packages"=pkg_repl("gnome-python2","2.6.0-3","i386");
"/software/packages"=pkg_repl("gnome-python2-bonobo","2.6.0-3","i386");
"/software/packages"=pkg_repl("gnome-python2-canvas","2.6.0-3","i386");
"/software/packages"=pkg_repl("gnome-python2-gtkhtml2","2.6.0-3","i386");
"/software/packages"=pkg_repl("gnome-vfs2","2.8.2-8.7.EL4","i386");
"/software/packages"=pkg_repl("gtk2","2.4.13-24.el4","i386");
"/software/packages"=pkg_repl("gtkhtml2","2.6.2-1","i386");
"/software/packages"=pkg_repl("libIDL","0.8.4-1","i386");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","i386");
"/software/packages"=pkg_repl("libbonobo","2.8.0-2","i386");
"/software/packages"=pkg_repl("libbonoboui","2.8.0.99cvs20040929-2","i386");
"/software/packages"=pkg_repl("libglade2","2.4.0-5","i386");
"/software/packages"=pkg_repl("libgnome","2.8.0-2","i386");
"/software/packages"=pkg_repl("libgnomecanvas","2.8.0-1","i386");
"/software/packages"=pkg_repl("libgnomeui","2.8.0-1","i386");
"/software/packages"=pkg_repl("libwnck","2.8.1-7.el4","i386");
"/software/packages"=pkg_repl("mpage","2.5.4-2","i386");
"/software/packages"=pkg_repl("pango","1.6.0-9","i386");
"/software/packages"=pkg_repl("perl-DateManip","5.42a-3","noarch");
"/software/packages"=pkg_repl("perl-HTML-Parser","3.55-1.el4","i386");
"/software/packages"=pkg_repl("perl-HTML-Tagset","3.03-30","noarch");
"/software/packages"=pkg_repl("perl-Parse-Yapp","1.05-32","noarch");
"/software/packages"=pkg_repl("perl-XML-Dumper","0.71-2","noarch");
"/software/packages"=pkg_repl("perl-XML-Encoding","1.01-26","noarch");
"/software/packages"=pkg_repl("perl-XML-Parser","2.34-5","i386");
"/software/packages"=pkg_repl("perl-libwww-perl","5.79-5","noarch");
"/software/packages"=pkg_repl("perl-libxml-enno","1.02-31","noarch");
"/software/packages"=pkg_repl("perl-libxml-perl","0.07-30","noarch");
"/software/packages"=pkg_repl("pnm2ppa","1.04-11","i386");
"/software/packages"=pkg_repl("pygtk2","2.4.0-2.el4","i386");
"/software/packages"=pkg_repl("pygtk2-libglade","2.4.0-2.el4","i386");
"/software/packages"=pkg_repl("pyorbit","2.0.1-1","i386");
"/software/packages"=pkg_repl("samba","3.0.28-0.el4.9","i386");
"/software/packages"=pkg_repl("samba-common","3.0.28-0.el4.9","i386");
"/software/packages"=pkg_repl("shared-mime-info","0.15-10.1.el4","i386");
"/software/packages"=pkg_repl("startup-notification","0.7-1","i386");
"/software/packages"=pkg_repl("system-config-boot","0.2.7-1","i386");
"/software/packages"=pkg_repl("system-config-httpd","1.3.1-1","noarch");
"/software/packages"=pkg_repl("system-config-nfs","1.2.8-1","noarch");
"/software/packages"=pkg_repl("system-config-printer","0.6.116.10-1.2","i386");
"/software/packages"=pkg_repl("system-config-printer-gui","0.6.116.10-1.2","i386");
"/software/packages"=pkg_repl("system-config-samba","1.2.21-1.el4.1","noarch");
"/software/packages"=pkg_repl("system-config-securitylevel","1.4.19.2-1","i386");
"/software/packages"=pkg_repl("system-config-services","0.8.15-1","noarch");
"/software/packages"=pkg_repl("system-switch-mail","0.5.25-3","noarch");
"/software/packages"=pkg_repl("system-switch-mail-gnome","0.5.25-3","noarch");
"/software/packages"=pkg_repl("ttmkfdir","3.0.9-20.el4","i386");
"/software/packages"=pkg_repl("urw-fonts","2.2-6.1","noarch");
"/software/packages"=pkg_repl("usermode-gtk","1.74-2.el4.1","i386");
"/software/packages"=pkg_repl("xorg-x11-xauth","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xorg-x11-xfs","6.8.2-1.EL.52","i386");

