# Template generated by comps2pan.xsl - DO NOT EDIT
#
# From CD recording to playing audio CDs and multimedia files, this package group allows you to work with sound and video on the system.
#

unique template rpms/sound_and_video;

include { 'rpms/base' };
include { 'rpms/base_x' };

"/software/packages"=pkg_repl("HelixPlayer","1.0.6-0.EL4.2.0.2","i386");
"/software/packages"=pkg_repl("SDL","1.2.7-8","i386");
"/software/packages"=pkg_repl("alsa-utils","1.0.6-9","i386");
"/software/packages"=pkg_repl("arts","1.3.1-2","i386");
"/software/packages"=pkg_repl("aumix","2.8-9","i386");
"/software/packages"=pkg_repl("cdda2wav","2.01.1-5.0.EL4.4","i386");
"/software/packages"=pkg_repl("cdparanoia","alpha9.8-24","i386");
"/software/packages"=pkg_repl("cdparanoia-libs","alpha9.8-24","i386");
"/software/packages"=pkg_repl("cdrecord","2.01.1-5.0.EL4.4","i386");
"/software/packages"=pkg_repl("curl","7.12.1-11.el4","i386");
"/software/packages"=pkg_repl("dvd+rw-tools","5.21.4.10.8-4","i386");
"/software/packages"=pkg_repl("eel2","2.8.1-2","i386");
"/software/packages"=pkg_repl("flac","1.1.0-7.el4_5.2","i386");
"/software/packages"=pkg_repl("gdk-pixbuf","0.22.0-17.el4.3","i386");
"/software/packages"=pkg_repl("gstreamer","0.8.7-4.EL.0","i386");
"/software/packages"=pkg_repl("gstreamer-plugins","0.8.5-1.EL.1","i386");
"/software/packages"=pkg_repl("gstreamer-tools","0.8.7-4.EL.0","i386");
"/software/packages"=pkg_repl("gtk+","1.2.10-36","i386");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("k3b","0.11.14-6.RHEL4","i386");
"/software/packages"=pkg_repl("kdebase","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","i386");
"/software/packages"=pkg_repl("kdemultimedia","3.3.1-2","i386");
"/software/packages"=pkg_repl("libao","0.8.5-2.EL.0","i386");
"/software/packages"=pkg_repl("libdv","0.103-1","i386");
"/software/packages"=pkg_repl("libidn","0.5.6-1","i386");
"/software/packages"=pkg_repl("libmad","0.15.1b-3.SL","i386");
"/software/packages"=pkg_repl("libmng","1.0.8-1","i386");
"/software/packages"=pkg_repl("libmusicbrainz","2.0.2-11","i386");
"/software/packages"=pkg_repl("libraw1394","0.10.1-3","i386");
"/software/packages"=pkg_repl("libtheora","1.0alpha3-5","i386");
"/software/packages"=pkg_repl("mikmod","3.1.6-32.EL4","i386");
"/software/packages"=pkg_repl("mkisofs","2.01.1-5.0.EL4.4","i386");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","i386");
"/software/packages"=pkg_repl("rhythmbox","0.8.8-1","i386");
"/software/packages"=pkg_repl("sound-juicer","0.5.14-2.EL","i386");
"/software/packages"=pkg_repl("sox","12.17.5-3","i386");
"/software/packages"=pkg_repl("speex","1.0.4-4.el4_6.1","i386");
"/software/packages"=pkg_repl("vorbis-tools","1.0.1-4","i386");
"/software/packages"=pkg_repl("xcdroast","0.98a15-6","i386");
"/software/packages"=pkg_repl("xmms","1.2.10-9","i386");
"/software/packages"=pkg_repl("zisofs-tools","1.0.6-1","i386");

