# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This package group includes packages useful for use with Postgresql.
#

unique template rpms/sql_server;

include { 'rpms/base' };

"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","x86_64");
"/software/packages"=pkg_repl("arts","1.3.1-2","x86_64");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","x86_64");
"/software/packages"=pkg_repl("desktop-backgrounds-basic","2.0-26.2.3SL","noarch");
"/software/packages"=pkg_repl("esound","0.2.35-2","x86_64");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","x86_64");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("kdelibs","3.3.1-11.el4","x86_64");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","x86_64");
"/software/packages"=pkg_repl("libidn","0.5.6-1","x86_64");
"/software/packages"=pkg_repl("libmng","1.0.8-1","x86_64");
"/software/packages"=pkg_repl("libogg","1.1.2-1","x86_64");
"/software/packages"=pkg_repl("libvorbis","1.1.0-3.el4_6.1","x86_64");
"/software/packages"=pkg_repl("mx","2.0.5-3","x86_64");
"/software/packages"=pkg_repl("perl-DBD-Pg","1.31-6","x86_64");
"/software/packages"=pkg_repl("perl-DBI","1.40-9","x86_64");
"/software/packages"=pkg_repl("postgresql","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-contrib","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-docs","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-jdbc","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-libs","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-odbc","7.3-8.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("postgresql-pl","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-python","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-server","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-tcl","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("postgresql-test","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("qt","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("qt-ODBC","3.3.3-13.RHEL4","x86_64");
"/software/packages"=pkg_repl("redhat-artwork","0.120.1-1.2SL.2","x86_64");
"/software/packages"=pkg_repl("rhdb-utils","3.0-3","x86_64");
"/software/packages"=pkg_repl("tora","1.3.14.1-2","x86_64");
"/software/packages"=pkg_repl("unixODBC","2.2.11-1.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("unixODBC-kde","2.2.11-1.RHEL4.1","x86_64");

