# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This group includes text-based email, Web, and chat clients. These applications do not require the X Window System.
#

unique template rpms/text_internet;

include { 'rpms/base' };

"/software/packages"=pkg_repl("GConf2","2.8.1-2.el4","x86_64");
"/software/packages"=pkg_repl("ORBit2","2.12.0-3","x86_64");
"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","x86_64");
"/software/packages"=pkg_repl("atk","1.8.0-2","x86_64");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","x86_64");
"/software/packages"=pkg_repl("cadaver","0.22.1-3","x86_64");
"/software/packages"=pkg_repl("chkfontpath","1.10.0-2","x86_64");
"/software/packages"=pkg_repl("cpp","3.4.6-10","x86_64");
"/software/packages"=pkg_repl("elinks","0.9.2-3.3.5.2","x86_64");
"/software/packages"=pkg_repl("esound","0.2.35-2","x86_64");
"/software/packages"=pkg_repl("evolution28-atk","1.12.2-4.el4","x86_64");
"/software/packages"=pkg_repl("evolution28-cairo","1.2.4-6.el4","x86_64");
"/software/packages"=pkg_repl("evolution28-glib2","2.12.3-6.el4","x86_64");
"/software/packages"=pkg_repl("evolution28-gtk2","2.10.4-22.el4","x86_64");
"/software/packages"=pkg_repl("evolution28-pango","1.14.9-7.el4","x86_64");
"/software/packages"=pkg_repl("fetchmail","6.2.5-6.0.1.el4","x86_64");
"/software/packages"=pkg_repl("firefox","3.0.1-3.el4","x86_64");
"/software/packages"=pkg_repl("fonts-xorg-base","6.8.2-1.EL","noarch");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","x86_64");
"/software/packages"=pkg_repl("gnome-mime-data","2.4.1-5","x86_64");
"/software/packages"=pkg_repl("gnome-vfs2","2.8.2-8.7.EL4","x86_64");
"/software/packages"=pkg_repl("gtk2","2.4.13-24.el4","x86_64");
"/software/packages"=pkg_repl("hicolor-icon-theme","0.3-3","noarch");
"/software/packages"=pkg_repl("libIDL","0.8.4-1","x86_64");
"/software/packages"=pkg_repl("libbonobo","2.8.0-2","x86_64");
"/software/packages"=pkg_repl("libgnome","2.8.0-2","x86_64");
"/software/packages"=pkg_repl("mutt","1.4.1-12.0.3.el4","x86_64");
"/software/packages"=pkg_repl("neon","0.24.7-4","x86_64");
"/software/packages"=pkg_repl("nspr","4.7.0.99.2-2.el4","x86_64");
"/software/packages"=pkg_repl("nss","3.11.99.5-3.el4","x86_64");
"/software/packages"=pkg_repl("pango","1.6.0-9","x86_64");
"/software/packages"=pkg_repl("shared-mime-info","0.15-10.1.el4","x86_64");
"/software/packages"=pkg_repl("switchdesk","4.0.6-3","noarch");
"/software/packages"=pkg_repl("ttmkfdir","3.0.9-20.el4","x86_64");
"/software/packages"=pkg_repl("xinitrc","4.0.14.3-3","noarch");
"/software/packages"=pkg_repl("xorg-x11","6.8.2-1.EL.52","x86_64");
"/software/packages"=pkg_repl("xorg-x11-xfs","6.8.2-1.EL.52","x86_64");

