# Template generated by comps2pan.xsl - DO NOT EDIT
#
# This group includes text-based email, Web, and chat clients. These applications do not require the X Window System.
#

unique template rpms/text_internet;

include { 'rpms/base' };

"/software/packages"=pkg_repl("GConf2","2.8.1-2.el4","i386");
"/software/packages"=pkg_repl("ORBit2","2.12.0-3","i386");
"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","i386");
"/software/packages"=pkg_repl("atk","1.8.0-2","i386");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","i386");
"/software/packages"=pkg_repl("cadaver","0.22.1-3","i386");
"/software/packages"=pkg_repl("elinks","0.9.2-3.3.5.2","i386");
"/software/packages"=pkg_repl("esound","0.2.35-2","i386");
"/software/packages"=pkg_repl("fetchmail","6.2.5-6.0.1.el4","i386");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("gnome-keyring","0.4.0-1.2.EL4","i386");
"/software/packages"=pkg_repl("gnome-mime-data","2.4.1-5","i386");
"/software/packages"=pkg_repl("gnome-vfs2","2.8.2-8.7.EL4","i386");
"/software/packages"=pkg_repl("gtk2","2.4.13-24.el4","i386");
"/software/packages"=pkg_repl("libIDL","0.8.4-1","i386");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","i386");
"/software/packages"=pkg_repl("libbonobo","2.8.0-2","i386");
"/software/packages"=pkg_repl("libbonoboui","2.8.0.99cvs20040929-2","i386");
"/software/packages"=pkg_repl("libglade2","2.4.0-5","i386");
"/software/packages"=pkg_repl("libgnome","2.8.0-2","i386");
"/software/packages"=pkg_repl("libgnomecanvas","2.8.0-1","i386");
"/software/packages"=pkg_repl("libgnomeui","2.8.0-1","i386");
"/software/packages"=pkg_repl("mutt","1.4.1-12.0.3.el4","i386");
"/software/packages"=pkg_repl("neon","0.24.7-4","i386");
"/software/packages"=pkg_repl("nspr","4.7.0.99.2-2.el4","i386");
"/software/packages"=pkg_repl("nss","3.11.99.5-3.el4","i386");
"/software/packages"=pkg_repl("pango","1.6.0-9","i386");
"/software/packages"=pkg_repl("seamonkey","1.0.9-24.el4","i386");
"/software/packages"=pkg_repl("shared-mime-info","0.15-10.1.el4","i386");

