# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These tools allow you to run a Web server on the system.
#

unique template rpms/web_server;

include { 'rpms/base' };

"/software/packages"=pkg_repl("4Suite","1.0-3","x86_64");
"/software/packages"=pkg_repl("GConf2","2.8.1-2.el4","x86_64");
"/software/packages"=pkg_repl("ORBit2","2.12.0-3","x86_64");
"/software/packages"=pkg_repl("PyXML","0.8.3-6","x86_64");
"/software/packages"=pkg_repl("alchemist","1.0.34-1","x86_64");
"/software/packages"=pkg_repl("alsa-lib","1.0.6-5.RHEL4","x86_64");
"/software/packages"=pkg_repl("atk","1.8.0-2","x86_64");
"/software/packages"=pkg_repl("audiofile","0.2.6-1.el4.1","x86_64");
"/software/packages"=pkg_repl("crypto-utils","2.1-4.3.el4","x86_64");
"/software/packages"=pkg_repl("curl","7.12.1-11.el4","x86_64");
"/software/packages"=pkg_repl("distcache","1.4.5-6","x86_64");
"/software/packages"=pkg_repl("esound","0.2.35-2","x86_64");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","x86_64");
"/software/packages"=pkg_repl("gd","2.0.28-5.4E.el4_6.1","x86_64");
"/software/packages"=pkg_repl("gnome-keyring","0.4.0-1.2.EL4","x86_64");
"/software/packages"=pkg_repl("gnome-mime-data","2.4.1-5","x86_64");
"/software/packages"=pkg_repl("gnome-python2","2.6.0-3","x86_64");
"/software/packages"=pkg_repl("gnome-python2-bonobo","2.6.0-3","x86_64");
"/software/packages"=pkg_repl("gnome-python2-canvas","2.6.0-3","x86_64");
"/software/packages"=pkg_repl("gnome-vfs2","2.8.2-8.7.EL4","x86_64");
"/software/packages"=pkg_repl("gtk2","2.4.13-24.el4","x86_64");
"/software/packages"=pkg_repl("httpd","2.0.52-41.sl4","x86_64");
"/software/packages"=pkg_repl("httpd-manual","2.0.52-41.sl4","x86_64");
"/software/packages"=pkg_repl("httpd-suexec","2.0.52-41.sl4","x86_64");
"/software/packages"=pkg_repl("libIDL","0.8.4-1","x86_64");
"/software/packages"=pkg_repl("libart_lgpl","2.3.16-3","x86_64");
"/software/packages"=pkg_repl("libbonobo","2.8.0-2","x86_64");
"/software/packages"=pkg_repl("libbonoboui","2.8.0.99cvs20040929-2","x86_64");
"/software/packages"=pkg_repl("libglade2","2.4.0-5","x86_64");
"/software/packages"=pkg_repl("libgnome","2.8.0-2","x86_64");
"/software/packages"=pkg_repl("libgnomecanvas","2.8.0-1","x86_64");
"/software/packages"=pkg_repl("libgnomeui","2.8.0-1","x86_64");
"/software/packages"=pkg_repl("libidn","0.5.6-1","x86_64");
"/software/packages"=pkg_repl("mod_auth_kerb","5.0-1.3","x86_64");
"/software/packages"=pkg_repl("mod_auth_mysql","2.6.1-2.2","x86_64");
"/software/packages"=pkg_repl("mod_auth_pgsql","2.0.1-7.1","x86_64");
"/software/packages"=pkg_repl("mod_authz_ldap","0.26-2.1","x86_64");
"/software/packages"=pkg_repl("mod_perl","1.99_16-4.5","x86_64");
"/software/packages"=pkg_repl("mod_python","3.1.3-5.1","x86_64");
"/software/packages"=pkg_repl("mod_ssl","2.0.52-41.sl4","x86_64");
"/software/packages"=pkg_repl("mysql","4.1.22-2.el4.sl","x86_64");
"/software/packages"=pkg_repl("newt-perl","1.08-7","x86_64");
"/software/packages"=pkg_repl("pango","1.6.0-9","x86_64");
"/software/packages"=pkg_repl("perl-DBI","1.40-9","x86_64");
"/software/packages"=pkg_repl("perl-URI","1.30-4","noarch");
"/software/packages"=pkg_repl("php","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-ldap","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-mysql","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-odbc","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-pear","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("php-pgsql","4.3.9-3.22.12","x86_64");
"/software/packages"=pkg_repl("postgresql-libs","7.4.19-1.el4_6.1","x86_64");
"/software/packages"=pkg_repl("pygtk2","2.4.0-2.el4","x86_64");
"/software/packages"=pkg_repl("pygtk2-libglade","2.4.0-2.el4","x86_64");
"/software/packages"=pkg_repl("pyorbit","2.0.1-1","x86_64");
"/software/packages"=pkg_repl("shared-mime-info","0.15-10.1.el4","x86_64");
"/software/packages"=pkg_repl("squid","2.5.STABLE14-4.el4","x86_64");
"/software/packages"=pkg_repl("system-config-httpd","1.3.1-1","noarch");
"/software/packages"=pkg_repl("tux","3.2.18-2","x86_64");
"/software/packages"=pkg_repl("unixODBC","2.2.11-1.RHEL4.1","x86_64");
"/software/packages"=pkg_repl("webalizer","2.01_10-25","x86_64");

