# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/workstation_common;

include { 'rpms/dialup' };
include { 'rpms/office' };
include { 'rpms/base_x' };
include { 'rpms/sound_and_video' };
include { 'rpms/editors' };
include { 'rpms/admin_tools' };
include { 'rpms/printing' };
include { 'rpms/games' };
include { 'rpms/base' };
include { 'rpms/graphics' };
include { 'rpms/text_internet' };
include { 'rpms/graphical_internet' };
include { 'rpms/yum' };
include { 'rpms/apt_rpm' };


