# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These packages allow you to develop applications for the X Window System.
#

unique template rpms/x_software_development;

include { 'rpms/development_tools' };

"/software/packages"=pkg_repl("SDL","1.2.7-8","i386");
"/software/packages"=pkg_repl("SDL-devel","1.2.7-8","i386");
"/software/packages"=pkg_repl("Xaw3d","1.5-24","i386");
"/software/packages"=pkg_repl("Xaw3d-devel","1.5-24","i386");
"/software/packages"=pkg_repl("alsa-lib-devel","1.0.6-5.RHEL4","i386");
"/software/packages"=pkg_repl("fontconfig-devel","2.2.3-13.el4","i386");
"/software/packages"=pkg_repl("freetype-devel","2.1.9-8.el4.6","i386");
"/software/packages"=pkg_repl("gamin","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("gamin-devel","0.1.7-1.4.EL4","i386");
"/software/packages"=pkg_repl("gd-devel","2.0.28-5.4E.el4_6.1","i386");
"/software/packages"=pkg_repl("icon-slicer","0.3-6","i386");
"/software/packages"=pkg_repl("iiimf-libs","12.1-13.EL.7","i386");
"/software/packages"=pkg_repl("iiimf-libs-devel","12.1-13.EL.7","i386");
"/software/packages"=pkg_repl("libjpeg-devel","6b-33","i386");
"/software/packages"=pkg_repl("libmng-devel","1.0.8-1","i386");
"/software/packages"=pkg_repl("libpng-devel","1.2.7-3.el4_5.1","i386");
"/software/packages"=pkg_repl("libpng10","1.0.16-3.el4_5.1","i386");
"/software/packages"=pkg_repl("libpng10-devel","1.0.16-3.el4_5.1","i386");
"/software/packages"=pkg_repl("libtiff-devel","3.6.1-12.el4_7.2","i386");
"/software/packages"=pkg_repl("libungif","4.1.3-1.el4.2","i386");
"/software/packages"=pkg_repl("libungif-devel","4.1.3-1.el4.2","i386");
"/software/packages"=pkg_repl("netpbm","10.25-2.EL4.6.el4_6.1","i386");
"/software/packages"=pkg_repl("netpbm-devel","10.25-2.EL4.6.el4_6.1","i386");
"/software/packages"=pkg_repl("openmotif-devel","2.2.3-10.2.el4","i386");
"/software/packages"=pkg_repl("xorg-x11-deprecated-libs-devel","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xorg-x11-devel","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xorg-x11-sdk","6.8.2-1.EL.52","i386");
"/software/packages"=pkg_repl("xrestop","0.2-4","i386");

