# Template generated by comps2pan.xsl - DO NOT EDIT
#
# The XEmacs text editor.
#

unique template rpms/xemacs;

include { 'rpms/base' };

"/software/packages"=pkg_repl("Canna-libs","3.7p3-7.EL4","i386");
"/software/packages"=pkg_repl("FreeWnn-libs","1.10pl020-6.el4","i386");
"/software/packages"=pkg_repl("Xaw3d","1.5-24","i386");
"/software/packages"=pkg_repl("apel-xemacs","10.6-5","noarch");
"/software/packages"=pkg_repl("xemacs","21.4.15-11.EL4","i386");
"/software/packages"=pkg_repl("xemacs-common","21.4.15-11.EL4","i386");
"/software/packages"=pkg_repl("xemacs-el","21.4.15-11.EL4","i386");
"/software/packages"=pkg_repl("xemacs-info","21.4.15-11.EL4","i386");
"/software/packages"=pkg_repl("xemacs-sumo","20040818-2","noarch");

